---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dex.araihu.com
  resources:
  - dexconnectors
  - dexlocalusers
  - dexoauth2clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.araihu.com
  resources:
  - dexconnectors/finalizers
  - dexlocalusers/finalizers
  - dexoauth2clients/finalizers
  verbs:
  - update
- apiGroups:
  - dex.araihu.com
  resources:
  - dexconnectors/status
  - dexlocalusers/status
  - dexoauth2clients/status
  verbs:
  - get
  - patch
  - update
