apiVersion: dex.araihu.com/v1alpha1
kind: DexLocalUser
metadata:
  labels:
    app.kubernetes.io/name: dex-operator
    app.kubernetes.io/managed-by: kustomize
  name: dexlocaluser-sample
spec:
  email: user@example.invalid
  username: Example User
  password:
    generated:
      secretName: example-user-password
      length: 24
      characterSets:
      - letters
      - numbers
      - symbols
