apiVersion: dex.araihu.com/v1alpha1
kind: DexConnector
metadata:
  labels:
    app.kubernetes.io/name: dex-operator
    app.kubernetes.io/managed-by: kustomize
  name: dexconnector-sample
spec:
  id: example-oidc
  type: oidc
  name: Example OIDC
  configSecretRef:
    name: example-oidc-config
    key: config.json
  grantTypes:
  - authorization_code
