//go:build !ignore_autogenerated

/*
Copyright .

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnector) DeepCopyInto(out *DexConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnector.
func (in *DexConnector) DeepCopy() *DexConnector {
	if in == nil {
		return nil
	}
	out := new(DexConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnectorList) DeepCopyInto(out *DexConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnectorList.
func (in *DexConnectorList) DeepCopy() *DexConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnectorSpec) DeepCopyInto(out *DexConnectorSpec) {
	*out = *in
	out.ConfigSecretRef = in.ConfigSecretRef
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnectorSpec.
func (in *DexConnectorSpec) DeepCopy() *DexConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnectorStatus) DeepCopyInto(out *DexConnectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnectorStatus.
func (in *DexConnectorStatus) DeepCopy() *DexConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUser) DeepCopyInto(out *DexLocalUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUser.
func (in *DexLocalUser) DeepCopy() *DexLocalUser {
	if in == nil {
		return nil
	}
	out := new(DexLocalUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLocalUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUserList) DeepCopyInto(out *DexLocalUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexLocalUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUserList.
func (in *DexLocalUserList) DeepCopy() *DexLocalUserList {
	if in == nil {
		return nil
	}
	out := new(DexLocalUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLocalUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUserMFASpec) DeepCopyInto(out *DexLocalUserMFASpec) {
	*out = *in
	if in.RemoveAuthenticatorIDs != nil {
		in, out := &in.RemoveAuthenticatorIDs, &out.RemoveAuthenticatorIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoveWebAuthnCredentialIDs != nil {
		in, out := &in.RemoveWebAuthnCredentialIDs, &out.RemoveWebAuthnCredentialIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUserMFASpec.
func (in *DexLocalUserMFASpec) DeepCopy() *DexLocalUserMFASpec {
	if in == nil {
		return nil
	}
	out := new(DexLocalUserMFASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUserPasswordSpec) DeepCopyInto(out *DexLocalUserPasswordSpec) {
	*out = *in
	if in.HashSecretRef != nil {
		in, out := &in.HashSecretRef, &out.HashSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = new(GeneratedPasswordSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUserPasswordSpec.
func (in *DexLocalUserPasswordSpec) DeepCopy() *DexLocalUserPasswordSpec {
	if in == nil {
		return nil
	}
	out := new(DexLocalUserPasswordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUserSpec) DeepCopyInto(out *DexLocalUserSpec) {
	*out = *in
	in.Password.DeepCopyInto(&out.Password)
	if in.MFA != nil {
		in, out := &in.MFA, &out.MFA
		*out = new(DexLocalUserMFASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUserSpec.
func (in *DexLocalUserSpec) DeepCopy() *DexLocalUserSpec {
	if in == nil {
		return nil
	}
	out := new(DexLocalUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalUserStatus) DeepCopyInto(out *DexLocalUserStatus) {
	*out = *in
	if in.MFADevices != nil {
		in, out := &in.MFADevices, &out.MFADevices
		*out = make([]MFADeviceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalUserStatus.
func (in *DexLocalUserStatus) DeepCopy() *DexLocalUserStatus {
	if in == nil {
		return nil
	}
	out := new(DexLocalUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2Client) DeepCopyInto(out *DexOAuth2Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2Client.
func (in *DexOAuth2Client) DeepCopy() *DexOAuth2Client {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOAuth2Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ClientList) DeepCopyInto(out *DexOAuth2ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexOAuth2Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ClientList.
func (in *DexOAuth2ClientList) DeepCopy() *DexOAuth2ClientList {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOAuth2ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ClientSecretSpec) DeepCopyInto(out *DexOAuth2ClientSecretSpec) {
	*out = *in
	if in.ProvidedSecretRef != nil {
		in, out := &in.ProvidedSecretRef, &out.ProvidedSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = new(GeneratedOAuth2ClientSecretSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ClientSecretSpec.
func (in *DexOAuth2ClientSecretSpec) DeepCopy() *DexOAuth2ClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ClientSpec) DeepCopyInto(out *DexOAuth2ClientSpec) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TrustedPeers != nil {
		in, out := &in.TrustedPeers, &out.TrustedPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedConnectors != nil {
		in, out := &in.AllowedConnectors, &out.AllowedConnectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(DexOAuth2ClientSecretSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ClientSpec.
func (in *DexOAuth2ClientSpec) DeepCopy() *DexOAuth2ClientSpec {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ClientStatus) DeepCopyInto(out *DexOAuth2ClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ClientStatus.
func (in *DexOAuth2ClientStatus) DeepCopy() *DexOAuth2ClientStatus {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedOAuth2ClientSecretSpec) DeepCopyInto(out *GeneratedOAuth2ClientSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedOAuth2ClientSecretSpec.
func (in *GeneratedOAuth2ClientSecretSpec) DeepCopy() *GeneratedOAuth2ClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratedOAuth2ClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedPasswordSpec) DeepCopyInto(out *GeneratedPasswordSpec) {
	*out = *in
	if in.CharacterSets != nil {
		in, out := &in.CharacterSets, &out.CharacterSets
		*out = make([]PasswordCharacterSet, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedPasswordSpec.
func (in *GeneratedPasswordSpec) DeepCopy() *GeneratedPasswordSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratedPasswordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MFADeviceStatus) DeepCopyInto(out *MFADeviceStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.WebAuthnCredentials != nil {
		in, out := &in.WebAuthnCredentials, &out.WebAuthnCredentials
		*out = make([]WebAuthnCredentialStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MFADeviceStatus.
func (in *MFADeviceStatus) DeepCopy() *MFADeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MFADeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAuthnCredentialStatus) DeepCopyInto(out *WebAuthnCredentialStatus) {
	*out = *in
	if in.Transports != nil {
		in, out := &in.Transports, &out.Transports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAuthnCredentialStatus.
func (in *WebAuthnCredentialStatus) DeepCopy() *WebAuthnCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(WebAuthnCredentialStatus)
	in.DeepCopyInto(out)
	return out
}
